export const GET_PHOTO_LIST = 'GET_PHOTO_LIST';
export const GET_PHOTO_LIST_SUCCESS = 'GET_PHOTO_LIST_SUCCESS';
export const GET_PHOTO_LIST_FAILED = 'GET_PHOTO_LIST_FAILED';

export const ADD_COMMENT = 'ADD_COMMENT';
export const ADD_COMMENT_SUCCESS = 'ADD_COMMENT_SUCCESS';
export const ADD_COMMENT_FAILED = 'ADD_COMMENT_FAILED';

